Repository iguazio/dashboard-react-controls, pull requests merged in 2022-10, with the labels that each got.

#67 Fix [Tip] align icon to center
  src/lib/components/Tip/Tip.js
  src/lib/components/Tip/tip.scss
Labels: bug

#64 Impl [UI] Add/Change target path to register model, dataset and artifacts wizard
  src/lib/components/FormCombobox/FormCombobox.js
  src/lib/components/FormCombobox/formCombobox.scss
Labels: enhancement

#69 Impl [Modal] add sub title prop in the header
  src/lib/components/FormChipCell/FormChipCell.js
  src/lib/components/FormCombobox/FormCombobox.js
  src/lib/components/FormCombobox/formCombobox.scss
  src/lib/components/FormTextarea/formTextarea.scss
  src/lib/components/Modal/Modal.js
  src/lib/components/Modal/Modal.scss
  src/lib/components/Wizard/Wizard.js
Labels: bug, enhancement
