Repository iguazio/dashboard-react-controls, pull requests merged in 2024-10, with the labels that each got.

#321 Fix [UI] UI small fixes
  src/lib/components/FormChipCell/NewChipForm/NewChipForm.js
Labels: bug

#323 Fix [Tests] Add Branch Patterns for CI workflow pull_request Triggers in GitHub Action
  .github/workflows/ci.yaml
Labels: bug

#322 Fix [UI] UI small fixes `1.7.x`
  src/lib/components/FormChipCell/NewChipForm/NewChipForm.js
Labels: bug

#328 Fix [UI] Warning icon overlay on input text
  src/lib/components/Tooltip/Tooltip.js
Labels: bug

#326 Impl [NPM] Upgrade webpack package in DRC
  package.json
Labels: dependencies

#331 Impl [Workflows] Add retry option for workflows
  src/lib/images/rerun.svg
Labels: enhancement
