Repository iguazio/dashboard-react-controls, pull requests merged in 2024-09, with the labels that each got.

#312 Fix [DRC] Apply ESLint & Prettier Formatting Adjustments
  src/lib/components/ConfirmDialog/ConfirmDialog.js
  src/lib/components/ConfirmDialog/ConfirmDialog.stories.js
  src/lib/components/FormCheckBox/FormCheckbox.stories.js
  src/lib/components/FormChipCell/FormChip/FormChip.js
  src/lib/components/FormChipCell/FormChipCell.js
  src/lib/components/FormChipCell/FormChipCellView.js
  src/lib/components/FormChipCell/HiddenChipsBlock/HiddenChipsBlock.js
  src/lib/components/FormChipCell/NewChipForm/NewChipForm.js
  src/lib/components/FormChipCell/NewChipInput/NewChipInput.js
  src/lib/components/FormChipCell/formChipCell.util.js
  src/lib/components/FormCombobox/FormCombobox.js
  src/lib/components/FormCombobox/FormCombobox.stories.js
  src/lib/components/FormInput/FormInput.stories.js
  src/lib/components/FormInput/InputNumberButtons/InputNumberButtons.js
  src/lib/components/FormKeyValueTable/FormKeyValueTable.js
  src/lib/components/FormOnChange/FormOnChange.js
  src/lib/components/FormRadio/FormRadio.stories.js
  src/lib/components/FormSelect/FormSelect.js
  src/lib/components/FormSelect/FormSelect.stories.js
  src/lib/components/FormSelect/FormSelect.test.js
  src/lib/components/FormTextarea/FormTextarea.stories.js
  src/lib/components/FormToggle/FormToggle.js
  src/lib/components/Tip/Tip.js
  src/lib/components/Tip/Tip.stories.js
  src/lib/components/Tip/Tip.test.js
  src/lib/components/Tooltip/Tooltip.js
  src/lib/components/Tooltip/Tooltip.stories.js
  src/lib/components/Tooltip/tooltip.scss
  src/lib/components/TooltipTemplate/TextTooltipTemplate.js
  src/lib/components/Wizard/Wizard.js
  src/lib/components/Wizard/WizardSteps/WizardSteps.js
  src/lib/elements/FormActionButton/FormActionButton.js
  src/lib/elements/FormRowActions/FormRowActions.js
  src/lib/elements/SelectOption/SelectOption.test.js
  src/lib/hooks/useChipCell.hook.js
  src/lib/hooks/useFormTable.hook.js
  src/lib/scss/fonts.scss
  src/lib/scss/mixins.scss
  src/lib/scss/shadows.scss
  src/lib/types.js
  src/lib/utils/common.util.js
  src/lib/utils/form.util.js
  src/lib/utils/generateChipsList.util.js
  src/lib/utils/getFirstScrollableParent.util.js
  src/lib/utils/validation.util.js
Labels: enhancement

#311 Fix [Models endpoints monitoring, metrics] The 'Choose metrics' dropdown is closing unexpectedly
  src/lib/components/PopUpDialog/PopUpDialog.js
Labels: bug

#313 Fix [Round Icon] Tooltip doesn't disappear
  src/lib/components/Tooltip/Tooltip.js
Labels: bug

#315 Fix [UI] UI crash when closing pop-up dialog
  src/lib/components/PopUpDialog/PopUpDialog.js
Labels: bug

#316 Fix [Chips] Hidden chips block doesn't close
  src/lib/hooks/useChipCell.hook.js
Labels: bug

#319 Tests [UI] Add Initial Workflow to Enable GitHub Actions for Forked Repositories
  .github/workflows/ci.yaml
  .licenserc.json
Labels: Tests
