Repository iguazio/dashboard-react-controls, pull requests merged in 2025-04, with the labels that each got.

#380 Impl [Details] Move Redux to RTK
  src/lib/components/FormChipCell/FormChipCellView.js
Labels: cleanup

#385 Impl [LLM Prompt Artifact] Add navigation to LLM Prompt Artifacts screen
  src/lib/images/navbar/llm-prompt-icon.svg
Labels: enhancement

#382 Fix [Labels] Label size is badly calculated
  src/lib/components/FormChipCell/FormChip/FormChip.js
  src/lib/components/FormChipCell/NewChipForm/NewChipForm.js
Labels: bug

#384 Fix [Action bar] request is sent despite "name' filter is invalid
  src/lib/components/FormInput/FormInput.js
Labels: bug

#387 Impl [Monitoring application] Add Monitoring application page
  src/lib/images/navbar/model-monitoring.svg
Labels: enhancement

#391 Fix [Artifacts] Path dropdown doesn't close when clicking outside the field `1.8.x`
  src/lib/components/FormCombobox/FormCombobox.js
Labels: bug

#393 Fix [Artifacts] Path dropdown doesn't close when clicking outside the field `1.9.x`
  src/lib/components/FormCombobox/FormCombobox.js
Labels: bug

#392 Fix [Artifacts] Path dropdown doesn't close when clicking outside the field
  src/lib/components/FormCombobox/FormCombobox.jsx
  src/lib/components/FormInput/FormInput.jsx
  src/lib/elements/OptionsMenu/OptionsMenu.jsx
Labels: bug
